### ISSUE TITLE
Adicionar Dependabot to repo

### ISSUE THREAD

**Issue by mpinheir** [OsProgramadores/portalestagio#21]

**Comment by magnussolidus** [comment]
Vou atuar nessa issue. Caso não tenha as permissões necessárias, as solicitarei.

**Comment by magnussolidus** [comment]
Preciso das permissões de configuração do repositório para poder habilitar o dependabot aqui no projeto.
O arquivo YML necessário para que ele faça as verificações de atualização foi adicionado em um PR.

**Comment by magnussolidus** [comment]
Dependabot adicionado pelo @mpinheir, fechando a issue.
